[package]
name = "simulink-rs"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"
license = "MIT"
description = "Simulink C to Rust macros"
repository = "https://github.com/rconan/simulink-rs"
documentation = "https://docs.rs/simulink-rs"
